version: '3.8'

services:
  bug-tracker-client:
    image: ghcr.io/apinanyogaratnam/bug-tracker-client:latest
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/bug-tracker-client:/app

  bug-tracker-service:
    image: ghcr.io/apinanyogaratnam/bug-tracker-service:latest
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/bug-tracker-service:/app

volumes:
  bug-tracker-client: ~
  bug-tracker-service: ~
